def get_singer_by_state(state):
    singers_by_state = {
        'Alabama': 'Lionel Richie',
        'Alabama'.casefold(): 'Lionel Richie',
        'Alaska'.casefold: 'Jewel',
        'Alaska': 'Jewel',
        'Arizona': 'Linda Ronstadt',
        'Arizona'.casefold(): 'Linda Ronstadt',
        'Arkansas': 'Johnny Cash',
        'California': 'Beyoncé',
        'California'.casefold(): 'Beyoncé',
        'Colorado': 'John Denver',
        'Colorado'.casefold(): 'John Denver',
        'Connecticut': 'Moby',
        'Connecticut'.casefold(): 'Moby',
        'Delaware': 'George Thorogood',
        'Delaware'.casefold(): 'George Thorogood',
        'Florida': 'Ariana Grande',
        'Florida'.casefold(): 'Ariana Grande',
        'Georgia': 'Ray Charles',
        'Georgia'.casefold(): 'Ray Charles',
        'Hawaii': 'Bruno Mars',
        'Hawaii'.casefold(): 'Bruno Mars',
        'Idaho': 'Paul Revere',
        'Idaho'.casefold(): 'Paul Revere',
        'Illinois': 'Kanye West',
        'Illinois'.casefold(): 'Kanye West',
        'Indiana': 'Michael Jackson',
        'Indiana'.casefold(): 'Michael Jackson',
        'Iowa': 'Slipknot',
        'Iowa'.casefold(): 'Slipknot',
        'Kansas': 'Martina McBride',
        'Kansas'.casefold(): 'Martina McBride',
        'Kentucky': 'Loretta Lynn',
        'Kentucky'.casefold: 'Loretta Lynn',
        'Louisiana': 'Louis Armstrong',
        'Louisiana'.casefold(): 'Louis Armstrong',
        'Maine': 'Howie Day',
         'Maine'.casefold(): 'Howie Day',
        'Maryland': 'Billie Holiday',
        'Maryland'.casefold(): 'Billie Holiday',
        'Massachusetts': 'Aerosmith',
        'Massachusetts'.casefold(): 'Aerosmith',
        'Michigan': 'Stevie Wonder',
        'Michigan'.casefold(): 'Stevie Wonder',
        'Minnesota': 'Prince',
        'Minnesota'.casefold(): 'Prince',
        'Mississippi': 'Elvis Presley',
        'Mississippi'.casefold(): 'Elvis Presley',
        'Missouri': 'Chuck Berry',
        'Missouri'.casefold(): 'Chuck Berry',
        'Montana': 'Jeff Ament',
        'Montana'.casefold(): 'Jeff Ament',
        'Nebraska': 'Conor Oberst',
        'Nebraska'.casefold(): 'Conor Oberst',
        'Nevada': 'Brandon Flowers',
        'Nevada'.casefold(): 'Brandon Flowers',
        'New Hampshire': 'Ray LaMontagne',
        'New Hampshire'.casefold(): 'Ray LaMontagne',
        'New Jersey': 'Whitney Houston',
        'New Jersey'.casefold(): 'Whitney Houston',
        'New Mexico': 'Demi Lovato',
        'New Mexico'.casefold(): 'Demi Lovato',
        'New York': 'Billy Joel',
        'New York'.casefold(): 'Billy Joel',
        'North Carolina': 'Nina Simone',
        'North Carolina'.casefold(): 'Nina Simone',
        'North Dakota': 'Peggy Lee',
        'North Dakota'.casefold(): 'Peggy Lee',
        'Ohio': 'John Legend',
        'Ohio'.casefold(): 'John Legend',
        'Oklahoma': 'Garth Brooks',
        'Oklahoma'.casefold(): 'Garth Brooks',
        'Oregon': 'Elliott Smith',
        'Oregon'.casefold(): 'Elliott Smith',
        'Pennsylvania': 'Taylor Swift',
        'Pennsylvania'.casefold(): 'Taylor Swift',
        'Rhode Island': 'Nelson Eddy',
        'Rhode Island'.casefold(): 'Nelson Eddy',
        'South Carolina': 'James Brown',
        'South Carolina'.casefold(): 'James Brown',
        'South Dakota': 'Shawn Colvin',
        'South Dakota'.casefold(): 'Shawn Colvin',
        'Tennessee': 'Dolly Parton',
        'Tennessee'.casefold(): 'Dolly Parton',
        'Texas': 'Willie Nelson',
        'Texas'.casefold(): 'Willie Nelson',
        'Utah': 'David Archuleta',
        'Utah'.casefold(): 'David Archuleta',
        'Vermont': 'Grace Potter',
        'Vermont'.casefold(): 'Grace Potter',
        'Virginia': 'Missy Elliott',
        'Virginia'.casefold(): 'Missy Elliott',
        'Washington': 'Jimi Hendrix',
        'Washington'.casefold(): 'Jimi Hendrix',
        'West Virginia': 'Brad Paisley',
        'West Virginia'.casefold(): 'Brad Paisley',
        'Wisconsin': 'Les Paul',
        'Wisconsin'.casefold(): 'Les Paul',
        'Wyoming': 'Chris LeDoux',
        'Wyoming'.casefold(): 'Chris LeDoux'
    }
   
    return singers_by_state.get(state, 'Singer not found for this state')


